### ISSUE TITLE
Exceptions with NC 16

### ISSUE THREAD

**Issue by sunchezz89** [a-schild/nextcloud-java-api#26] opened 2019-06-13 07:24 UTC
With the current version i cannnot make a connection to my nextcloud instance wich is a NC 16.0.1. 
I have tested this with every possible parameter for NextcloudConnector.
Either your API is complaining about an invalid SSL message (even if the boolean for ssl is set to false), or a bad request, 405, or 400 is catched.

Implementing the Sardine connection by myself with the same config, works instead.
```
String url = "subdomain.domain.tld";
client = SardineFactory.begin();
client.setCredentials(u, p);
client.enablePreemptiveAuthentication(url);
client.list("https://" + url + "/");
```

It seems that you are doing something with the uri, is that correct?

**Comment by a-schild** [comment] 2019-06-20 16:01
Can you please show the code you are using with the NC api to connect to your server?
In the URL the `remote.php/webdav/` and in other parts the `ocs/v1.php/apps/files_sharing/api/v1/` is handled by the library.

**Comment by sunchezz89** [comment] 2019-06-20 16:09
That's the code which did not work.

```
String server = "subdomain.domain.tld";
NextcloudConnector nc= new NextcloudConnector(server, true, 80, user, pw);
System.out.println(nc.listFolderContent());
```

**Comment by a-schild** [comment] 2019-06-20 17:10
With using https on port 80 it is very probably that it won't work, unless you configured your server to also accept https on port 80.

The default https port is 443.

`public NextcloudConnector(String serverName, boolean useHTTPS, int port, String userName, String password)`

**Comment by sunchezz89** [comment] 2019-06-20 17:14
I know. Thanks :)
1. i configured the server this way and 
2. i tired every option without ssl on port 80, with ssl on 443, with a different URL notation...  Everything.

And like i said, using the same configuration with plain Sardine, worked.

**Comment by a-schild** [comment] 2019-08-23 07:00
Without some code to reproduce the problem we can't help you.
Will close this issue in 1-2 weeks

**Comment by danieledivito** [comment] 2019-09-06 19:48
I have the same trouble.
It seems the trouble comes from src/main/java/org/aarboard/nextcloud/api/webdav/AWebdavHandler.java  buildWebdavPath method. URIBuilder returns a path like this https://server:443remote.php/webdav/folder_name
URI path is missing "/" before remote.php/webdav

This impact every webdav calls

**Comment by a-schild** [comment] 2019-09-17 07:17
This  issue id definitively not comming from this libarry, but from the http client URIBuilder.
Looks like there is a change in behaviour in some of the 4.5.2 - 4.5.9 versions.

In nextcloud api we now specify the version to 4.5.10 which does work as intended.
Could you please test with the new 11.1.0-SNAPSHOT release?

If it still fails, please check what httpclient version your project is including

**Comment by a-schild** [comment] 2020-01-15 10:27
Closing because no answer on question

**Closed by a-schild** 2020-01-15 10:27 UTC
